[package]
name = "aqevia-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
aqevia-kernel = { path = "../kernel" }
aqevia-router = { path = "../router" }
aqevia-transport = { path = "../transport" }
